version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    networks:
      - frontend-pub
networks:
  frontend-pub:
    external: true